version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 30
    directory: /
    schedule:
      interval: daily
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    open-pull-requests-limit: 30
    directory: /
    schedule:
      interval: daily
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch