name: Dependabot Auto Merge Branches
on:
  pull_request_target:
    types: [labeled, edited]

jobs:
  merge:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    name: Dependabot Merge Branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install

      - name: Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          command: merge
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}